# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "TODO-change-this"
name = "editions-dev-workshop"
handle = "TODO-change-this"
application_url = "https://example.com/"
embedded = true

[build]
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [ "https://example.com/api/auth" ]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
